Repository mit-ll-responsible-ai/hydra-zen, pull requests merged in 2023-02, with the labels that each got.

#406 Fix failing CI
  .pre-commit-config.yaml
  src/hydra_zen/_hydra_overloads.py
  src/hydra_zen/_launch.py
  src/hydra_zen/_utils/coerce.py
  src/hydra_zen/structured_configs/_implementations.py
  src/hydra_zen/structured_configs/_utils.py
  src/hydra_zen/typing/_builds_overloads.py
  tests/annotations/declarations.py
  tests/custom_strategies.py
  tests/pyright_utils.py
  tests/test_compatibility/test_hydra_supports_partial.py
  tests/test_compatibility/test_omegaconf_830.py
  tests/test_compatibility/test_primitive_support.py
  tests/test_config_value_validation.py
  tests/test_dataclass_semantics.py
  tests/test_hydra_behaviors.py
  tests/test_make_config.py
  tests/test_signature_parsing.py
  tests/test_third_party/test_type_validators.py
  tests/test_third_party/test_using_pydantic.py
  tests/test_utils.py
  tests/test_validation.py
  tests/test_zen.py
  tests/test_zen_processing/test_inheritance.py
  tests/test_zen_processing/test_zen_wrappers.py
Labels: test suite, repo/project

#313 Allow dictionary for overrides in `launch`
  docs/source/explanation/type_refinement.rst
  docs/source/how_to/pytorch_lightning.rst
  src/hydra_zen/__init__.py
  src/hydra_zen/_launch.py
  tests/annotations/declarations.py
  tests/test_launch/test_dict_overrides.py
Labels: enhancement

#414 Add support for jax 0.4.0
  src/hydra_zen/structured_configs/_implementations.py
Labels: enhancement, 3rd party issue

#409 Use Self annotation in store self-partialing
  .github/workflows/tox_run.yml
  docs/source/changes.rst
  src/hydra_zen/wrapper/_implementations.py
  tests/__init__.py
  tests/annotations/declarations.py
  tests/annotations/mypy_checks.py
Labels: type-checking

#418 Add type conversion support for `InitVar`
  src/hydra_zen/structured_configs/_utils.py
  tests/test_utils.py
Labels: enhancement
