Repository mit-ll-responsible-ai/hydra-zen, pull requests merged in 2023-01, with the labels that each got.

#373 Update tutorials and how-to for v0.9.0
  docs/source/changes.rst
  docs/source/how_to/partial_config.rst
  docs/source/how_to/pytorch_lightning.rst
  docs/source/tutorials/add_cli.rst
  docs/source/tutorials/basic_app.rst
  docs/source/tutorials/config_groups.rst
  docs/source/tutorials/hierarchy.rst
  docs/source/tutorials/inject_wrapper.rst
  src/hydra_zen/wrapper/_implementations.py
  tests/test_make_config.py
Labels: documentation

#374 test that docs build in CI; update some docstrings; update pyright scan utils
  .github/workflows/tox_run.yml
  docs/source/how_to/pytorch_lightning.rst
  pyproject.toml
  src/hydra_zen/wrapper/_implementations.py
  tests/pyright_utils.py
Labels: documentation, test suite, type-checking

#376 update actions caching based on pyproject.toml
  .github/workflows/tox_run.yml
  pyproject.toml
Labels: test suite

#377 Fix pyright scanning and consolidate typecheck action logic
  .github/dependabot.yml
  .github/workflows/nightly.yml
  .github/workflows/tox_run.yml
  deps/requirements-pyright.txt
  pyproject.toml
  tests/annotations/declarations.py
Labels: test suite, type-checking

#380 Ensure pytest is configured so `xfail_strict` is true
  tests/test_project.py
Labels: test suite

#390 pyright==1.2.288 ; fix type errors.
  deps/requirements-pyright.txt
  src/hydra_zen/structured_configs/_type_guards.py
  src/hydra_zen/structured_configs/_utils.py
  src/hydra_zen/typing/_implementations.py
  src/hydra_zen/wrapper/_implementations.py
Labels: type-checking

#398 Add Examples to Docs
  docs/source/api_reference.rst
  docs/source/how_to/configure_hydra.rst
  docs/source/how_to/configuring_experiments.rst
  docs/source/how_to/using_scikit_learn.rst
  docs/source/how_tos.rst
  docs/source/store.rst
  docs/source/tutorials/basic_app.rst
  docs/source/tutorials/config_groups.rst
  pyproject.toml
  src/hydra_zen/wrapper/_implementations.py
Labels: documentation

#401 Infer name/group for storing HydraConf instances/subclasses
  src/hydra_zen/wrapper/_implementations.py
  tests/example_app/change_hydra_config.py
  tests/test_signature_parsing.py
  tests/test_store.py
Labels: enhancement
